<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="CitizenFX.FiveM.Client" />
    <PackageReference Include="MenuAPI.FiveM.Enhanced" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\vMenu.Enhanced.NoClip\vMenu.Enhanced.NoClip.csproj" />
  </ItemGroup>
</Project>
