namespace vMenu.Enhanced.Data.PedModels;

public sealed record PedScenario(string Label, string Name, bool PositionBased = false);

public static class PedScenarios
{
    public static readonly PedScenario[] All =
    [
        new("AA Drink Coffee", "WORLD_HUMAN_AA_COFFEE"),
        new("AA Smoke Cig", "WORLD_HUMAN_AA_SMOKE"),
        new("Binoculars", "WORLD_HUMAN_BINOCULARS"),
        new("Bum Freeway", "WORLD_HUMAN_BUM_FREEWAY"),
        new("Bum Slumped", "WORLD_HUMAN_BUM_SLUMPED"),
        new("Bum Standing", "WORLD_HUMAN_BUM_STANDING"),
        new("Bum Wash", "WORLD_HUMAN_BUM_WASH"),
        new("Car Park Attendant", "WORLD_HUMAN_CAR_PARK_ATTENDANT"),
        new("Cheering", "WORLD_HUMAN_CHEERING"),
        new("Clipboard", "WORLD_HUMAN_CLIPBOARD"),
        new("Constant Drilling", "WORLD_HUMAN_CONST_DRILL"),
        new("Cop Idle", "WORLD_HUMAN_COP_IDLES"),
        new("Drinking", "WORLD_HUMAN_DRINKING"),
        new("Drug Dealer", "WORLD_HUMAN_DRUG_DEALER"),
        new("Drug Dealer Hard", "WORLD_HUMAN_DRUG_DEALER_HARD"),
        new("Mobile Film Shocking", "WORLD_HUMAN_MOBILE_FILM_SHOCKING"),
        new("Gardener Leaf Blower", "WORLD_HUMAN_GARDENER_LEAF_BLOWER"),
        new("Gardener Plant", "WORLD_HUMAN_GARDENER_PLANT"),
        new("Golf Player", "WORLD_HUMAN_GOLF_PLAYER"),
        new("Guard Patrol", "WORLD_HUMAN_GUARD_PATROL"),
        new("Guard Stand", "WORLD_HUMAN_GUARD_STAND"),
        new("Hammering", "WORLD_HUMAN_HAMMERING"),
        new("Hang Out Street", "WORLD_HUMAN_HANG_OUT_STREET"),
        new("Hiker Standing", "WORLD_HUMAN_HIKER_STANDING"),
        new("Human Statue", "WORLD_HUMAN_HUMAN_STATUE"),
        new("Janitor", "WORLD_HUMAN_JANITOR"),
        new("Jog Standing", "WORLD_HUMAN_JOG_STANDING"),
        new("Leaning", "WORLD_HUMAN_LEANING"),
        new("Maid Clean", "WORLD_HUMAN_MAID_CLEAN"),
        new("Muscle Flex", "WORLD_HUMAN_MUSCLE_FLEX"),
        new("Muscle Free Weights", "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS"),
        new("Musician", "WORLD_HUMAN_MUSICIAN"),
        new("Paparazzi", "WORLD_HUMAN_PAPARAZZI"),
        new("Partying", "WORLD_HUMAN_PARTYING"),
        new("Picnic", "WORLD_HUMAN_PICNIC"),
        new("Prostitute High Class", "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS"),
        new("Prostitute Low Class", "WORLD_HUMAN_PROSTITUTE_LOW_CLASS"),
        new("Pushups", "WORLD_HUMAN_PUSH_UPS"),
        new("Seat Ledge", "WORLD_HUMAN_SEAT_LEDGE", true),
        new("Seat Steps", "WORLD_HUMAN_SEAT_STEPS", true),
        new("Seat Wall", "WORLD_HUMAN_SEAT_WALL", true),
        new("Security Shine Torch", "WORLD_HUMAN_SECURITY_SHINE_TORCH"),
        new("Situps", "WORLD_HUMAN_SIT_UPS"),
        new("Smoking", "WORLD_HUMAN_SMOKING"),
        new("Smoking Pot", "WORLD_HUMAN_SMOKING_POT"),
        new("Stand Fire", "WORLD_HUMAN_STAND_FIRE"),
        new("Stand Fishing", "WORLD_HUMAN_STAND_FISHING"),
        new("Stand Impatient", "WORLD_HUMAN_STAND_IMPATIENT"),
        new("Stand Impatient Upright", "WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT"),
        new("Stand Mobile", "WORLD_HUMAN_STAND_MOBILE"),
        new("Stand Mobile Upright", "WORLD_HUMAN_STAND_MOBILE_UPRIGHT"),
        new("Stripclub Watch Stand", "WORLD_HUMAN_STRIP_WATCH_STAND"),
        new("Stupor", "WORLD_HUMAN_STUPOR"),
        new("Sunbathe", "WORLD_HUMAN_SUNBATHE"),
        new("Sunbathe Back", "WORLD_HUMAN_SUNBATHE_BACK"),
        new("Tennis Player", "WORLD_HUMAN_TENNIS_PLAYER"),
        new("Tourist Map", "WORLD_HUMAN_TOURIST_MAP"),
        new("Tourist Mobile", "WORLD_HUMAN_TOURIST_MOBILE"),
        new("Vehicle Mechanic", "WORLD_HUMAN_VEHICLE_MECHANIC"),
        new("Welding", "WORLD_HUMAN_WELDING"),
        new("Window Shop Browse", "WORLD_HUMAN_WINDOW_SHOP_BROWSE"),
        new("Yoga", "WORLD_HUMAN_YOGA"),
        new("ATM", "PROP_HUMAN_ATM"),
        new("BBQ", "PROP_HUMAN_BBQ"),
        new("Bum Bin", "PROP_HUMAN_BUM_BIN"),
        new("Bum Shopping Cart", "PROP_HUMAN_BUM_SHOPPING_CART"),
        new("Muscle Chin Ups", "PROP_HUMAN_MUSCLE_CHIN_UPS"),
        new("Muscle Chin Ups Army", "PROP_HUMAN_MUSCLE_CHIN_UPS_ARMY"),
        new("Muscle Chin Ups Prison", "PROP_HUMAN_MUSCLE_CHIN_UPS_PRISON"),
        new("Parking Meter", "PROP_HUMAN_PARKING_METER"),
        new("Seat Armchair", "PROP_HUMAN_SEAT_ARMCHAIR", true),
        new("Seat Bar", "PROP_HUMAN_SEAT_BAR", true),
        new("Seat Bench", "PROP_HUMAN_SEAT_BENCH", true),
        new("Seat Bus Stop Wait", "PROP_HUMAN_SEAT_BUS_STOP_WAIT", true),
        new("Seat Chair", "PROP_HUMAN_SEAT_CHAIR", true),
        new("Seat Chair Upright", "PROP_HUMAN_SEAT_CHAIR_UPRIGHT", true),
        new("Seat MP Player", "PROP_HUMAN_SEAT_CHAIR_MP_PLAYER", true),
        new("Seat Computer", "PROP_HUMAN_SEAT_COMPUTER", true),
        new("Seat Deckchair", "PROP_HUMAN_SEAT_DECKCHAIR", true),

        // Not positioned, unlike the other sit-down ones: it puts these three through the prop.
        new("Seat Deckchair Drink", "PROP_HUMAN_SEAT_DECKCHAIR_DRINK"),
        new("Seat Muscle Bench Press", "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS"),
        new("Seat Muscle Bench Press Prison", "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS_PRISON"),

        new("Seat Stripclub Watch", "PROP_HUMAN_SEAT_STRIP_WATCH", true),
        new("Seat Sunlounger", "PROP_HUMAN_SEAT_SUNLOUNGER", true),
        new("Stand Impatient (Prop)", "PROP_HUMAN_STAND_IMPATIENT"),
        new("Cross Road Wait", "CODE_HUMAN_CROSS_ROAD_WAIT"),
        new("Medic Kneel", "CODE_HUMAN_MEDIC_KNEEL"),
        new("Medic Tend To Dead", "CODE_HUMAN_MEDIC_TEND_TO_DEAD"),
        new("Medic Time Of Death", "CODE_HUMAN_MEDIC_TIME_OF_DEATH"),
        new("Police Crowd Control", "CODE_HUMAN_POLICE_CROWD_CONTROL"),
        new("Police Investigate", "CODE_HUMAN_POLICE_INVESTIGATE"),
    ];
}
