<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsResourceBundleProject>true</IsResourceBundleProject>
    <BundleSide>server</BundleSide>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CitizenFX.FiveM.Server" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\vMenu.Enhanced.Logging\vMenu.Enhanced.Logging.csproj" />
    <ProjectReference Include="..\vMenu.Enhanced.Actions.Server\vMenu.Enhanced.Actions.Server.csproj" />
    <ProjectReference Include="..\vMenu.Enhanced.BrokenNatives.Server\vMenu.Enhanced.BrokenNatives.Server.csproj" />
    <ProjectReference Include="..\vMenu.Enhanced.Configuration.Server\vMenu.Enhanced.Configuration.Server.csproj" />
    <ProjectReference Include="..\vMenu.Enhanced.Permissions.Server\vMenu.Enhanced.Permissions.Server.csproj" />
    <ProjectReference Include="..\vMenu.Enhanced.Plugins.Server\vMenu.Enhanced.Plugins.Server.csproj" />
    <ProjectReference Include="..\vMenu.Enhanced.Ticks.Server\vMenu.Enhanced.Ticks.Server.csproj" />
  </ItemGroup>
</Project>
