using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace vMenu.Enhanced.NativeHooks.Generator;

/// <summary>
/// Emits an internal <em>vMenu.Enhanced.Native</em> class that forwards to the real
/// <em>CitizenFX.FiveM.Client.Native</em> with <em>NativeHook</em> calls wrapped around it.
///
/// Call sites need no change because C# resolves a bare type name against the enclosing
/// namespaces before it looks at the using directives, and every client file sits inside
/// vMenu.Enhanced. The generated class therefore wins over the one the using pulls in.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class NativeForwarderGenerator : IIncrementalGenerator
{
    private const string Symbol = "NATIVE_HOOKS";
    private const string NativeType = "CitizenFX.FiveM.Client.Native";
    private const string HookType = "global::vMenu.Enhanced.NativeHooks.NativeHook";

    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enabled = context.ParseOptionsProvider.Select(static (options, _) =>
            options.PreprocessorSymbolNames.Contains(Symbol));

        var names = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is MemberAccessExpressionSyntax
                {
                    Expression: IdentifierNameSyntax { Identifier.ValueText: "Native" },
                },
                static (ctx, _) => ((MemberAccessExpressionSyntax)ctx.Node).Name.Identifier.ValueText)
            .Collect();

        var input = enabled.Combine(names).Combine(context.CompilationProvider);

        context.RegisterSourceOutput(input, static (spc, value) =>
        {
            var ((isEnabled, used), compilation) = value;
            if (!isEnabled)
            {
                return;
            }

            var source = Render(compilation, used);
            if (source is not null)
            {
                spc.AddSource("vMenu.Enhanced.Native.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private static string? Render(Compilation compilation, ImmutableArray<string> used)
    {
        if (used.IsDefaultOrEmpty)
        {
            return null;
        }

        var native = compilation.GetTypeByMetadataName(NativeType);
        if (native is null)
        {
            return null;
        }

        var wanted = new HashSet<string>(used, StringComparer.Ordinal);

        var methods = native.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(method => method.IsStatic
                && method.MethodKind == MethodKind.Ordinary
                && method.DeclaredAccessibility == Accessibility.Public
                && wanted.Contains(method.Name)
                && CanForward(method))
            .OrderBy(method => method.Name, StringComparer.Ordinal)
            .ThenBy(method => method.Parameters.Length)
            .ToList();

        if (methods.Count == 0)
        {
            return null;
        }

        var builder = new StringBuilder();
        builder.AppendLine("""
            // <auto-generated/>
            #nullable enable

            namespace vMenu.Enhanced;

            internal static class Native
            {
            """);

        for (var i = 0; i < methods.Count; i++)
        {
            if (i > 0)
            {
                builder.AppendLine();
            }

            Append(builder, methods[i]);
        }

        builder.AppendLine("}");

        // AppendLine writes the platform newline while the raw strings carry whatever
        // this file is saved with, so without this the output ends up mixing the two.
        return builder.Replace("\r\n", "\n").ToString();
    }

    private static bool CanForward(IMethodSymbol method)
    {
        if (method.ReturnsByRef || method.ReturnsByRefReadonly || method.IsGenericMethod)
        {
            return false;
        }

        return method.Parameters.All(parameter => !parameter.IsParams
            && parameter.Type.TypeKind != TypeKind.Pointer
            && parameter.Type.TypeKind != TypeKind.FunctionPointer);
    }

    private static void Append(StringBuilder builder, IMethodSymbol method)
    {
        var name = method.Name;
        var returnType = method.ReturnsVoid ? "void" : method.ReturnType.ToDisplayString(TypeFormat);
        var parameters = string.Join(", ", method.Parameters.Select(FormatParameter));
        var arguments = string.Join(", ", method.Parameters.Select(FormatArgument));
        var result = method.ReturnsVoid ? string.Empty : "return ";

        builder.AppendLine($$"""
            internal static {{returnType}} {{name}}({{parameters}})
            {
                {{HookType}}.Before("{{name}}");
                try
                {
                    {{result}}global::{{NativeType}}.{{name}}({{arguments}});
                }
                catch (global::System.Exception exception)
                {
                    {{HookType}}.OnException("{{name}}", exception);
                    throw;
                }
                finally
                {
                    {{HookType}}.After("{{name}}");
                }
            }
        """);
    }

    private static string FormatParameter(IParameterSymbol parameter) =>
        $"{Modifier(parameter.RefKind)}{parameter.Type.ToDisplayString(TypeFormat)} {Escape(parameter.Name)}";

    private static string FormatArgument(IParameterSymbol parameter) =>
        $"{Modifier(parameter.RefKind)}{Escape(parameter.Name)}";

    private static string Modifier(RefKind kind) => kind switch
    {
        RefKind.Out => "out ",
        RefKind.Ref => "ref ",
        RefKind.In => "in ",
        _ => string.Empty,
    };

    private static string Escape(string name) =>
        SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None ? name : "@" + name;
}
