<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CitizenFX.FiveM.Client" />
    <PackageReference Include="MenuAPI.FiveM.Enhanced" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\vMenu.Enhanced.Configuration\vMenu.Enhanced.Configuration.csproj" />
    <ProjectReference Include="..\vMenu.Enhanced.Permissions\vMenu.Enhanced.Permissions.csproj" />
  </ItemGroup>

</Project>
