using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CitizenFX.Core;
using static CitizenFX.Core.Native.API;

namespace vMenuClient
{
    public struct ValidWeapon
    {
        public uint Hash;
        public string Name;
        public Dictionary<string, uint> Components;
        public Permission Perm;
    }

    public class ValidWeapons
    {
        private ValidWeapon[] _validWeaponsList = new ValidWeapon[82 - 4 + 7];

        public ValidWeapon[] WeaponList
        {
            get
            {
                return _validWeaponsList ?? new ValidWeapon[0];
            }
        }

        public ValidWeapons()
        {
            var num = 0;

            foreach (var weapon in Weapons)
            {
                string realName = weapon.Key;
                string localizedName = weaponNames[realName];
                if (localizedName != "Invalid" && localizedName != "Night Vision" && localizedName != "Unarmed" && localizedName != "" && localizedName != "Parachute")
                {
                    uint hash = weapon.Value;
                    Dictionary<string, uint> componentHashes = new Dictionary<string, uint>();
                    foreach (var comp in weaponComponents)
                    {
                        if (DoesWeaponTakeWeaponComponent(hash, comp.Value))
                        {
                            if (!componentHashes.ContainsKey(weaponComponentNames[comp.Key]))
                            {
                                componentHashes.Add(weaponComponentNames[comp.Key], comp.Value);
                            }
                        }
                    }
                    ValidWeapon vw = new ValidWeapon()
                    {
                        Hash = hash,
                        Name = localizedName,
                        Components = componentHashes,
                        Perm = weaponPermissions[realName]
                    };
                    _validWeaponsList[num] = vw;
                    num++;
                }
            }
        }

        #region Weapon names, hashes and localized names (+ all components & tints).
        #region weapon names
        public static readonly Dictionary<string, string> weaponNames = new Dictionary<string, string>()
        {
            ["APPistol"] = "AP Pistol",
            ["AdvancedRifle"] = "Advanced Rifle",
            ["AssaultRifle"] = "Assault Rifle",
            ["AssaultRifleMk2"] = "Assault Rifle Mk II",
            ["AssaultSMG"] = "Assault SMG",
            ["AssaultShotgun"] = "Assault Shotgun",
            ["BZGas"] = "BZ Gas",
            ["Ball"] = "Ball",
            ["Bat"] = "Baseball Bat",
            ["BattleAxe"] = "Battle Axe",
            ["Bottle"] = "Bottle",
            ["BullpupRifle"] = "Bullpup Rifle",
            ["BullpupRifleMk2"] = "Bullpup Rifle Mk II",
            ["BullpupShotgun"] = "Bullpup Shotgun",
            ["CarbineRifle"] = "Carbine Rifle",
            ["CarbineRifleMk2"] = "Carbine Rifle Mk II",
            ["CombatMG"] = "Combat MG",
            ["CombatMGMk2"] = "Combat MG Mk II",
            ["CombatPDW"] = "Combat PDW",
            ["CombatPistol"] = "Combat Pistol",
            ["CompactGrenadeLauncher"] = "Compact Grenade Launcher",
            ["CompactRifle"] = "Compact Rifle",
            ["Crowbar"] = "Crowbar",
            ["Dagger"] = "Antique Cavalry Dagger",
            ["DoubleAction"] = "Double Action Revolver",
            ["DoubleBarrelShotgun"] = "Double Barrel Shotgun",
            ["FireExtinguisher"] = "Fire Extinguisher",
            ["Firework"] = "Firework Launcher",
            ["Flare"] = "Flare",
            ["FlareGun"] = "Flare Gun",
            ["Flashlight"] = "Flashlight",
            ["GolfClub"] = "Golf Club",
            ["Grenade"] = "Grenade",
            ["GrenadeLauncher"] = "Grenade Launcher",
            ["GrenadeLauncherSmoke"] = "Invalid",
            ["Gusenberg"] = "Gusenberg Sweeper",
            ["Hammer"] = "Hammer",
            ["Hatchet"] = "Hatchet",
            ["HeavyPistol"] = "Heavy Pistol",
            ["HeavyShotgun"] = "Heavy Shotgun",
            ["HeavySniper"] = "Heavy Sniper",
            ["HeavySniperMk2"] = "Heavy Sniper Mk II",
            ["HomingLauncher"] = "Homing Launcher",
            ["Knife"] = "Knife",
            ["KnuckleDuster"] = "Knuckle Duster",
            ["MG"] = "MG",
            ["Machete"] = "Machete",
            ["MachinePistol"] = "Machine Pistol",
            ["MarksmanPistol"] = "Marksman Pistol",
            ["MarksmanRifle"] = "Marksman Rifle",
            ["MarksmanRifleMk2"] = "Marksman Rifle Mk II",
            ["MicroSMG"] = "Micro SMG",
            ["MiniSMG"] = "Mini SMG",
            ["Minigun"] = "Minigun",
            ["Molotov"] = "Molotov",
            ["Musket"] = "Musket",
            ["NightVision"] = "Night Vision",
            ["Nightstick"] = "Nightstick",
            ["Parachute"] = "Parachute",
            ["PetrolCan"] = "Jerry Can",
            ["PipeBomb"] = "Pipe Bomb",
            ["Pistol"] = "Pistol",
            ["Pistol50"] = "Pistol .50",
            ["PistolMk2"] = "Pistol Mk II",
            ["PoolCue"] = "Pool Cue",
            ["ProximityMine"] = "Proximity Mine",
            ["PumpShotgun"] = "Pump Shotgun",
            ["PumpShotgunMk2"] = "Pump Shotgun Mk II",
            ["RPG"] = "RPG",
            ["Railgun"] = "Railgun",
            ["Revolver"] = "Heavy Revolver",
            ["RevolverMk2"] = "Heavy Revolver Mk II",
            ["SMG"] = "SMG",
            ["SMGMk2"] = "SMG Mk II",
            ["SniperRifle"] = "Sniper Rifle",
            ["SNSPistol"] = "SNS Pistol",
            ["SNSPistolMk2"] = "SNS Pistol Mk II",
            ["SawnOffShotgun"] = "Sawed-Off Shotgun",
            ["SmokeGrenade"] = "Tear Gas",
            ["Snowball"] = "Snowball",
            ["SpecialCarbine"] = "Special Carbine",
            ["SpecialCarbineMk2"] = "Special Carbine Mk II",
            ["StickyBomb"] = "Sticky Bomb",
            ["StunGun"] = "Stun Gun",
            ["SweeperShotgun"] = "Sweeper Shotgun",
            ["SwitchBlade"] = "Switchblade",
            ["Unarmed"] = "Unarmed",
            ["VintagePistol"] = "Vintage Pistol",
            ["Wrench"] = "Pipe Wrench",
        };
        #endregion

        #region weapon permissions
        public static readonly Dictionary<string, Permission> weaponPermissions = new Dictionary<string, Permission>()
        {
            ["APPistol"] = Permission.WPAPPistol,
            ["AdvancedRifle"] = Permission.WPAdvancedRifle,
            ["AssaultRifle"] = Permission.WPAssaultRifle,
            ["AssaultRifleMk2"] = Permission.WPAssaultRifleMk2,
            ["AssaultSMG"] = Permission.WPAssaultSMG,
            ["AssaultShotgun"] = Permission.WPAssaultShotgun,
            ["BZGas"] = Permission.WPBZGas,
            ["Ball"] = Permission.WPBall,
            ["Bat"] = Permission.WPBat,
            ["BattleAxe"] = Permission.WPBattleAxe,
            ["Bottle"] = Permission.WPBottle,
            ["BullpupRifle"] = Permission.WPBullpupRifle,
            ["BullpupRifleMk2"] = Permission.WPBullpupRifleMk2,
            ["BullpupShotgun"] = Permission.WPBullpupShotgun,
            ["CarbineRifle"] = Permission.WPCarbineRifle,
            ["CarbineRifleMk2"] = Permission.WPCarbineRifleMk2,
            ["CombatMG"] = Permission.WPCombatMG,
            ["CombatMGMk2"] = Permission.WPCombatMGMk2,
            ["CombatPDW"] = Permission.WPCombatPDW,
            ["CombatPistol"] = Permission.WPCombatPistol,
            ["CompactGrenadeLauncher"] = Permission.WPCompactGrenadeLauncher,
            ["CompactRifle"] = Permission.WPCompactRifle,
            ["Crowbar"] = Permission.WPCrowbar,
            ["Dagger"] = Permission.WPDagger,
            ["DoubleAction"] = Permission.WPDoubleAction,
            ["DoubleBarrelShotgun"] = Permission.WPDoubleBarrelShotgun,
            ["FireExtinguisher"] = Permission.WPFireExtinguisher,
            ["Firework"] = Permission.WPFirework,
            ["Flare"] = Permission.WPFlare,
            ["FlareGun"] = Permission.WPFlareGun,
            ["Flashlight"] = Permission.WPFlashlight,
            ["GolfClub"] = Permission.WPGolfClub,
            ["Grenade"] = Permission.WPGrenade,
            ["GrenadeLauncher"] = Permission.WPGrenadeLauncher,
            ["GrenadeLauncherSmoke"] = Permission.WPGrenadeLauncherSmoke,
            ["Gusenberg"] = Permission.WPGusenberg,
            ["Hammer"] = Permission.WPHammer,
            ["Hatchet"] = Permission.WPHatchet,
            ["HeavyPistol"] = Permission.WPHeavyPistol,
            ["HeavyShotgun"] = Permission.WPHeavyShotgun,
            ["HeavySniper"] = Permission.WPHeavySniper,
            ["HeavySniperMk2"] = Permission.WPHeavySniperMk2,
            ["HomingLauncher"] = Permission.WPHomingLauncher,
            ["Knife"] = Permission.WPKnife,
            ["KnuckleDuster"] = Permission.WPKnuckleDuster,
            ["MG"] = Permission.WPMG,
            ["Machete"] = Permission.WPMachete,
            ["MachinePistol"] = Permission.WPMachinePistol,
            ["MarksmanPistol"] = Permission.WPMarksmanPistol,
            ["MarksmanRifle"] = Permission.WPMarksmanRifle,
            ["MarksmanRifleMk2"] = Permission.WPMarksmanRifleMk2,
            ["MicroSMG"] = Permission.WPMicroSMG,
            ["MiniSMG"] = Permission.WPMiniSMG,
            ["Minigun"] = Permission.WPMinigun,
            ["Molotov"] = Permission.WPMolotov,
            ["Musket"] = Permission.WPMusket,
            ["NightVision"] = Permission.WPNightVision,
            ["Nightstick"] = Permission.WPNightstick,
            ["Parachute"] = Permission.WPParachute,
            ["PetrolCan"] = Permission.WPPetrolCan,
            ["PipeBomb"] = Permission.WPPipeBomb,
            ["Pistol"] = Permission.WPPistol,
            ["Pistol50"] = Permission.WPPistol50,
            ["PistolMk2"] = Permission.WPPistolMk2,
            ["PoolCue"] = Permission.WPPoolCue,
            ["ProximityMine"] = Permission.WPProximityMine,
            ["PumpShotgun"] = Permission.WPPumpShotgun,
            ["PumpShotgunMk2"] = Permission.WPPumpShotgunMk2,
            ["RPG"] = Permission.WPRPG,
            ["Railgun"] = Permission.WPRailgun,
            ["Revolver"] = Permission.WPRevolver,
            ["RevolverMk2"] = Permission.WPRevolverMk2,
            ["SMG"] = Permission.WPSMG,
            ["SMGMk2"] = Permission.WPSMGMk2,
            ["SNSPistol"] = Permission.WPSNSPistol,
            ["SNSPistolMk2"] = Permission.WPSNSPistolMk2,
            ["SawnOffShotgun"] = Permission.WPSawnOffShotgun,
            ["SmokeGrenade"] = Permission.WPSmokeGrenade,
            ["SniperRifle"] = Permission.WPSniperRifle,
            ["Snowball"] = Permission.WPSnowball,
            ["SpecialCarbine"] = Permission.WPSpecialCarbine,
            ["SpecialCarbineMk2"] = Permission.WPSpecialCarbineMk2,
            ["StickyBomb"] = Permission.WPStickyBomb,
            ["StunGun"] = Permission.WPStunGun,
            ["SweeperShotgun"] = Permission.WPSweeperShotgun,
            ["SwitchBlade"] = Permission.WPSwitchBlade,
            ["Unarmed"] = Permission.WPUnarmed,
            ["VintagePistol"] = Permission.WPVintagePistol,
            ["Wrench"] = Permission.WPWrench,
        };
        #endregion

        #region weapons (name to hash)
        public static readonly Dictionary<string, uint> Weapons = new Dictionary<string, uint>()
        {
            ["AdvancedRifle"] = 2937143193,
            ["APPistol"] = 584646201,
            ["AssaultRifle"] = 3220176749,
            ["AssaultRifleMk2"] = 961495388,
            ["AssaultShotgun"] = 3800352039,
            ["AssaultSMG"] = 4024951519,
            ["Ball"] = 600439132,
            ["Bat"] = 2508868239,
            ["BattleAxe"] = 3441901897,
            ["Bottle"] = 4192643659,
            ["BullpupRifle"] = 2132975508,
            ["BullpupRifleMk2"] = (uint)GetHashKey("WEAPON_BULLPUPRIFLE_MK2"),
            ["BullpupShotgun"] = 2640438543,
            ["BZGas"] = 2694266206,
            ["CarbineRifle"] = 2210333304,
            ["CarbineRifleMk2"] = 4208062921,
            ["CombatMG"] = 2144741730,
            ["CombatMGMk2"] = 3686625920,
            ["CombatPDW"] = 171789620,
            ["CombatPistol"] = 1593441988,
            ["CompactGrenadeLauncher"] = 125959754,
            ["CompactRifle"] = 1649403952,
            ["Crowbar"] = 2227010557,
            ["Dagger"] = 2460120199,
            ["DoubleAction"] = (uint)GetHashKey("WEAPON_DOUBLEACTION"),
            ["DoubleBarrelShotgun"] = 4019527611,
            ["FireExtinguisher"] = 101631238,
            ["Firework"] = 2138347493,
            ["Flare"] = 1233104067,
            ["FlareGun"] = 1198879012,
            ["Flashlight"] = 2343591895,
            ["GolfClub"] = 1141786504,
            ["Grenade"] = 2481070269,
            ["GrenadeLauncher"] = 2726580491,
            ["GrenadeLauncherSmoke"] = 1305664598,
            ["Gusenberg"] = 1627465347,
            ["Hammer"] = 1317494643,
            ["Hatchet"] = 4191993645,
            ["HeavyPistol"] = 3523564046,
            ["HeavyShotgun"] = 984333226,
            ["HeavySniper"] = 205991906,
            ["HeavySniperMk2"] = 177293209,
            ["HomingLauncher"] = 1672152130,
            ["Knife"] = 2578778090,
            ["KnuckleDuster"] = 3638508604,
            ["Machete"] = 3713923289,
            ["MachinePistol"] = 3675956304,
            ["MarksmanPistol"] = 3696079510,
            ["MarksmanRifle"] = 3342088282,
            ["MarksmanRifleMk2"] = (uint)GetHashKey("WEAPON_MARKSMANRIFLE_MK2"),
            ["MG"] = 2634544996,
            ["MicroSMG"] = 324215364,
            ["Minigun"] = 1119849093,
            ["MiniSMG"] = 3173288789,
            ["Molotov"] = 615608432,
            ["Musket"] = 2828843422,
            ["Nightstick"] = 1737195953,
            ["NightVision"] = 2803906140,
            ["Parachute"] = 4222310262,
            ["PetrolCan"] = 883325847,
            ["PipeBomb"] = 3125143736,
            ["Pistol"] = 453432689,
            ["Pistol50"] = 2578377531,
            ["PistolMk2"] = 3219281620,
            ["PoolCue"] = 2484171525,
            ["ProximityMine"] = 2874559379,
            ["PumpShotgun"] = 487013001,
            ["PumpShotgunMk2"] = (uint)GetHashKey("WEAPON_PUMPSHOTGUN_MK2"),
            ["Railgun"] = 1834241177,
            ["Revolver"] = 3249783761,
            ["RevolverMk2"] = (uint)GetHashKey("WEAPON_REVOLVER_MK2"),
            ["RPG"] = 2982836145,
            ["SawnOffShotgun"] = 2017895192,
            ["SMG"] = 736523883,
            ["SMGMk2"] = 2024373456,
            ["SmokeGrenade"] = 4256991824,
            ["SniperRifle"] = 100416529,
            ["Snowball"] = 126349499,
            ["SNSPistol"] = 3218215474,
            ["SNSPistolMk2"] = (uint)GetHashKey("WEAPON_SNSPISTOL_MK2"),
            ["SpecialCarbine"] = 3231910285,
            ["SpecialCarbineMk2"] = (uint)GetHashKey("WEAPON_SPECIALCARBINE_MK2"),
            ["StickyBomb"] = 741814745,
            ["StunGun"] = 911657153,
            ["SweeperShotgun"] = 317205821,
            ["SwitchBlade"] = 3756226112,
            ["Unarmed"] = 2725352035,
            ["VintagePistol"] = 137902532,
            ["Wrench"] = 419712736
        };
        #endregion

        #region weapon components
        public static readonly Dictionary<string, uint> weaponComponents = new Dictionary<string, uint>()
        {

            ["COMPONENT_PISTOL_CLIP_01"] = (uint)GetHashKey("COMPONENT_PISTOL_CLIP_01"),
            ["COMPONENT_PISTOL_CLIP_02"] = (uint)GetHashKey("COMPONENT_PISTOL_CLIP_02"),
            ["COMPONENT_PISTOL_VARMOD_LUXE"] = (uint)GetHashKey("COMPONENT_PISTOL_VARMOD_LUXE"),

            ["COMPONENT_PISTOL50_CLIP_01"] = (uint)GetHashKey("COMPONENT_PISTOL50_CLIP_01"),
            ["COMPONENT_PISTOL50_CLIP_02"] = (uint)GetHashKey("COMPONENT_PISTOL50_CLIP_02"),
            ["COMPONENT_PISTOL50_VARMOD_LUXE"] = (uint)GetHashKey("COMPONENT_PISTOL50_VARMOD_LUXE"),

            ["COMPONENT_COMBATPISTOL_CLIP_01"] = (uint)GetHashKey("COMPONENT_COMBATPISTOL_CLIP_01"),
            ["COMPONENT_COMBATPISTOL_CLIP_02"] = (uint)GetHashKey("COMPONENT_COMBATPISTOL_CLIP_02"),
            ["COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER"] = (uint)GetHashKey("COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER"),

            ["COMPONENT_APPISTOL_CLIP_01"] = (uint)GetHashKey("COMPONENT_APPISTOL_CLIP_01"),
            ["COMPONENT_APPISTOL_CLIP_02"] = (uint)GetHashKey("COMPONENT_APPISTOL_CLIP_02"),
            ["COMPONENT_APPISTOL_VARMOD_LUXE"] = (uint)GetHashKey("COMPONENT_APPISTOL_VARMOD_LUXE"),

            ["COMPONENT_SMG_CLIP_01"] = (uint)GetHashKey("COMPONENT_SMG_CLIP_01"),
            ["COMPONENT_SMG_CLIP_02"] = (uint)GetHashKey("COMPONENT_SMG_CLIP_02"),
            ["COMPONENT_SMG_CLIP_03"] = (uint)GetHashKey("COMPONENT_SMG_CLIP_03"),
            ["COMPONENT_AT_SCOPE_MACRO_02"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_MACRO_02"),
            ["COMPONENT_SMG_VARMOD_LUXE"] = (uint)GetHashKey("COMPONENT_SMG_VARMOD_LUXE"),

            ["COMPONENT_MICROSMG_CLIP_01"] = (uint)GetHashKey("COMPONENT_MICROSMG_CLIP_01"),
            ["COMPONENT_MICROSMG_CLIP_02"] = (uint)GetHashKey("COMPONENT_MICROSMG_CLIP_02"),
            ["COMPONENT_AT_SCOPE_MACRO"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_MACRO"),
            ["COMPONENT_MICROSMG_VARMOD_LUXE"] = (uint)GetHashKey("COMPONENT_MICROSMG_VARMOD_LUXE"),

            ["COMPONENT_ASSAULTSMG_CLIP_01"] = (uint)GetHashKey("COMPONENT_ASSAULTSMG_CLIP_01"),
            ["COMPONENT_ASSAULTSMG_CLIP_02"] = (uint)GetHashKey("COMPONENT_ASSAULTSMG_CLIP_02"),
            ["COMPONENT_AT_SCOPE_MACRO"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_MACRO"),
            ["COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER"] = (uint)GetHashKey("COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER"),

            ["COMPONENT_MG_CLIP_01"] = (uint)GetHashKey("COMPONENT_MG_CLIP_01"),
            ["COMPONENT_MG_CLIP_02"] = (uint)GetHashKey("COMPONENT_MG_CLIP_02"),
            ["COMPONENT_AT_SCOPE_SMALL_02"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_SMALL_02"),
            ["COMPONENT_MG_VARMOD_LOWRIDER"] = (uint)GetHashKey("COMPONENT_MG_VARMOD_LOWRIDER"),

            ["COMPONENT_COMBATMG_CLIP_01"] = (uint)GetHashKey("COMPONENT_COMBATMG_CLIP_01"),
            ["COMPONENT_COMBATMG_CLIP_02"] = (uint)GetHashKey("COMPONENT_COMBATMG_CLIP_02"),

            ["COMPONENT_ASSAULTRIFLE_CLIP_01"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_CLIP_01"),
            ["COMPONENT_ASSAULTRIFLE_CLIP_02"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_CLIP_02"),
            ["COMPONENT_ASSAULTRIFLE_CLIP_03"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_CLIP_03"),
            ["COMPONENT_AT_SCOPE_MACRO"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_MACRO"),
            ["COMPONENT_ASSAULTRIFLE_VARMOD_LUXE"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_VARMOD_LUXE"),

            ["COMPONENT_CARBINERIFLE_CLIP_01"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_CLIP_01"),
            ["COMPONENT_CARBINERIFLE_CLIP_02"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_CLIP_02"),
            ["COMPONENT_CARBINERIFLE_CLIP_03"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_CLIP_03"),
            ["COMPONENT_CARBINERIFLE_VARMOD_LUXE"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_VARMOD_LUXE"),

            ["COMPONENT_ADVANCEDRIFLE_CLIP_01"] = (uint)GetHashKey("COMPONENT_ADVANCEDRIFLE_CLIP_01"),
            ["COMPONENT_ADVANCEDRIFLE_CLIP_02"] = (uint)GetHashKey("COMPONENT_ADVANCEDRIFLE_CLIP_02"),
            ["COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE"] = (uint)GetHashKey("COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE"),

            ["COMPONENT_ASSAULTSHOTGUN_CLIP_01"] = (uint)GetHashKey("COMPONENT_ASSAULTSHOTGUN_CLIP_01"),
            ["COMPONENT_ASSAULTSHOTGUN_CLIP_02"] = (uint)GetHashKey("COMPONENT_ASSAULTSHOTGUN_CLIP_02"),

            ["COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE"] = (uint)GetHashKey("COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE"),

            ["COMPONENT_AT_SR_SUPP"] = (uint)GetHashKey("COMPONENT_AT_SR_SUPP"),
            ["COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER"),

            ["COMPONENT_AT_SCOPE_LARGE"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_LARGE"),
            ["COMPONENT_SNIPERRIFLE_VARMOD_LUXE"] = (uint)GetHashKey("COMPONENT_SNIPERRIFLE_VARMOD_LUXE"),

            ["COMPONENT_AT_SCOPE_LARGE"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_LARGE"),

            ["COMPONENT_AT_SCOPE_MACRO"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_MACRO"),
            ["COMPONENT_AT_SCOPE_MACRO_02"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_MACRO_02"),
            ["COMPONENT_AT_SCOPE_SMALL_02"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_SMALL_02"),
            ["COMPONENT_AT_SCOPE_LARGE"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_LARGE"),

            ["COMPONENT_AT_SR_SUPP"] = (uint)GetHashKey("COMPONENT_AT_SR_SUPP"),



            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CAMO"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_02"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CAMO_02"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_03"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CAMO_03"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_04"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CAMO_04"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_05"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CAMO_05"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_06"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CAMO_06"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_07"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CAMO_07"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_08"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CAMO_08"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_09"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CAMO_09"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_10"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CAMO_10"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CLIP_01"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CLIP_01"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CLIP_02"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CLIP_02"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER"] = (uint)GetHashKey("COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER"),
            ["COMPONENT_AT_AR_AFGRIP"] = (uint)GetHashKey("COMPONENT_AT_AR_AFGRIP"),
            ["COMPONENT_AT_AR_AFGRIP_02"] = (uint)GetHashKey("COMPONENT_AT_AR_AFGRIP_02"),
            ["COMPONENT_AT_AR_BARREL_01"] = (uint)GetHashKey("COMPONENT_AT_AR_BARREL_01"),
            ["COMPONENT_AT_AR_BARREL_02"] = (uint)GetHashKey("COMPONENT_AT_AR_BARREL_02"),
            ["COMPONENT_AT_AR_FLSH"] = (uint)GetHashKey("COMPONENT_AT_AR_FLSH"),
            ["COMPONENT_AT_AR_SUPP"] = (uint)GetHashKey("COMPONENT_AT_AR_SUPP"),
            ["COMPONENT_AT_AR_SUPP_02"] = (uint)GetHashKey("COMPONENT_AT_AR_SUPP_02"),
            ["COMPONENT_AT_BP_BARREL_01"] = (uint)GetHashKey("COMPONENT_AT_BP_BARREL_01"),
            ["COMPONENT_AT_BP_BARREL_02"] = (uint)GetHashKey("COMPONENT_AT_BP_BARREL_02"),
            ["COMPONENT_AT_CR_BARREL_01"] = (uint)GetHashKey("COMPONENT_AT_CR_BARREL_01"),
            ["COMPONENT_AT_CR_BARREL_02"] = (uint)GetHashKey("COMPONENT_AT_CR_BARREL_02"),
            ["COMPONENT_AT_MG_BARREL_01"] = (uint)GetHashKey("COMPONENT_AT_MG_BARREL_01"),
            ["COMPONENT_AT_MG_BARREL_02"] = (uint)GetHashKey("COMPONENT_AT_MG_BARREL_02"),
            ["COMPONENT_AT_MRFL_BARREL_01"] = (uint)GetHashKey("COMPONENT_AT_MRFL_BARREL_01"),
            ["COMPONENT_AT_MRFL_BARREL_02"] = (uint)GetHashKey("COMPONENT_AT_MRFL_BARREL_02"),
            ["COMPONENT_AT_MUZZLE_01"] = (uint)GetHashKey("COMPONENT_AT_MUZZLE_01"),
            ["COMPONENT_AT_MUZZLE_02"] = (uint)GetHashKey("COMPONENT_AT_MUZZLE_02"),
            ["COMPONENT_AT_MUZZLE_03"] = (uint)GetHashKey("COMPONENT_AT_MUZZLE_03"),
            ["COMPONENT_AT_MUZZLE_04"] = (uint)GetHashKey("COMPONENT_AT_MUZZLE_04"),
            ["COMPONENT_AT_MUZZLE_05"] = (uint)GetHashKey("COMPONENT_AT_MUZZLE_05"),
            ["COMPONENT_AT_MUZZLE_06"] = (uint)GetHashKey("COMPONENT_AT_MUZZLE_06"),
            ["COMPONENT_AT_MUZZLE_07"] = (uint)GetHashKey("COMPONENT_AT_MUZZLE_07"),
            ["COMPONENT_AT_MUZZLE_08"] = (uint)GetHashKey("COMPONENT_AT_MUZZLE_08"),
            ["COMPONENT_AT_MUZZLE_09"] = (uint)GetHashKey("COMPONENT_AT_MUZZLE_09"),
            ["COMPONENT_AT_PI_COMP"] = (uint)GetHashKey("COMPONENT_AT_PI_COMP"),
            ["COMPONENT_AT_PI_COMP_02"] = (uint)GetHashKey("COMPONENT_AT_PI_COMP_02"),
            ["COMPONENT_AT_PI_COMP_03"] = (uint)GetHashKey("COMPONENT_AT_PI_COMP_03"),
            ["COMPONENT_AT_PI_FLSH"] = (uint)GetHashKey("COMPONENT_AT_PI_FLSH"),
            ["COMPONENT_AT_PI_FLSH_02"] = (uint)GetHashKey("COMPONENT_AT_PI_FLSH_02"),
            ["COMPONENT_AT_PI_FLSH_03"] = (uint)GetHashKey("COMPONENT_AT_PI_FLSH_03"),
            ["COMPONENT_AT_PI_RAIL"] = (uint)GetHashKey("COMPONENT_AT_PI_RAIL"),
            ["COMPONENT_AT_PI_RAIL_02"] = (uint)GetHashKey("COMPONENT_AT_PI_RAIL_02"),
            ["COMPONENT_AT_PI_SUPP"] = (uint)GetHashKey("COMPONENT_AT_PI_SUPP"),
            ["COMPONENT_AT_PI_SUPP_02"] = (uint)GetHashKey("COMPONENT_AT_PI_SUPP_02"),
            ["COMPONENT_AT_SB_BARREL_01"] = (uint)GetHashKey("COMPONENT_AT_SB_BARREL_01"),
            ["COMPONENT_AT_SB_BARREL_02"] = (uint)GetHashKey("COMPONENT_AT_SB_BARREL_02"),
            ["COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM"),
            ["COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2"),
            ["COMPONENT_AT_SCOPE_LARGE_MK2"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_LARGE_MK2"),
            ["COMPONENT_AT_SCOPE_MACRO_02_MK2"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_MACRO_02_MK2"),
            ["COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2"),
            ["COMPONENT_AT_SCOPE_MACRO_MK2"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_MACRO_MK2"),
            ["COMPONENT_AT_SCOPE_MAX"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_MAX"),
            ["COMPONENT_AT_SCOPE_MEDIUM"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_MEDIUM"),
            ["COMPONENT_AT_SCOPE_MEDIUM_MK2"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_MEDIUM_MK2"),
            ["COMPONENT_AT_SCOPE_NV"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_NV"),
            ["COMPONENT_AT_SCOPE_SMALL"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_SMALL"),
            ["COMPONENT_AT_SCOPE_SMALL_MK2"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_SMALL_MK2"),
            ["COMPONENT_AT_SCOPE_SMALL_SMG_MK2"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_SMALL_SMG_MK2"),
            ["COMPONENT_AT_SCOPE_THERMAL"] = (uint)GetHashKey("COMPONENT_AT_SCOPE_THERMAL"),
            ["COMPONENT_AT_SC_BARREL_01"] = (uint)GetHashKey("COMPONENT_AT_SC_BARREL_01"),
            ["COMPONENT_AT_SC_BARREL_02"] = (uint)GetHashKey("COMPONENT_AT_SC_BARREL_02"),
            ["COMPONENT_AT_SIGHTS"] = (uint)GetHashKey("COMPONENT_AT_SIGHTS"),
            ["COMPONENT_AT_SIGHTS_SMG"] = (uint)GetHashKey("COMPONENT_AT_SIGHTS_SMG"),
            ["COMPONENT_AT_SR_BARREL_01"] = (uint)GetHashKey("COMPONENT_AT_SR_BARREL_01"),
            ["COMPONENT_AT_SR_BARREL_02"] = (uint)GetHashKey("COMPONENT_AT_SR_BARREL_02"),
            ["COMPONENT_AT_SR_SUPP_03"] = (uint)GetHashKey("COMPONENT_AT_SR_SUPP_03"),
            ["COMPONENT_BULLPUPRIFLE_CLIP_01"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_CLIP_01"),
            ["COMPONENT_BULLPUPRIFLE_CLIP_02"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_CLIP_02"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CAMO"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_02"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CAMO_02"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_03"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CAMO_03"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_04"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CAMO_04"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_05"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CAMO_05"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_06"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CAMO_06"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_07"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CAMO_07"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_08"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CAMO_08"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_09"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CAMO_09"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_10"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CAMO_10"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CLIP_01"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CLIP_01"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CLIP_02"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CLIP_02"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER"),
            ["COMPONENT_BULLPUPRIFLE_VARMOD_LOW"] = (uint)GetHashKey("COMPONENT_BULLPUPRIFLE_VARMOD_LOW"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CAMO"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_02"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CAMO_02"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_03"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CAMO_03"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_04"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CAMO_04"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_05"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CAMO_05"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_06"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CAMO_06"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_07"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CAMO_07"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_08"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CAMO_08"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_09"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CAMO_09"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_10"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CAMO_10"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01"),
            ["COMPONENT_CARBINERIFLE_MK2_CLIP_01"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CLIP_01"),
            ["COMPONENT_CARBINERIFLE_MK2_CLIP_02"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CLIP_02"),
            ["COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING"),
            ["COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ"),
            ["COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY"),
            ["COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER"] = (uint)GetHashKey("COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER"),
            ["COMPONENT_COMBATMG_MK2_CAMO"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CAMO"),
            ["COMPONENT_COMBATMG_MK2_CAMO_02"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CAMO_02"),
            ["COMPONENT_COMBATMG_MK2_CAMO_03"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CAMO_03"),
            ["COMPONENT_COMBATMG_MK2_CAMO_04"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CAMO_04"),
            ["COMPONENT_COMBATMG_MK2_CAMO_05"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CAMO_05"),
            ["COMPONENT_COMBATMG_MK2_CAMO_06"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CAMO_06"),
            ["COMPONENT_COMBATMG_MK2_CAMO_07"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CAMO_07"),
            ["COMPONENT_COMBATMG_MK2_CAMO_08"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CAMO_08"),
            ["COMPONENT_COMBATMG_MK2_CAMO_09"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CAMO_09"),
            ["COMPONENT_COMBATMG_MK2_CAMO_10"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CAMO_10"),
            ["COMPONENT_COMBATMG_MK2_CAMO_IND_01"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CAMO_IND_01"),
            ["COMPONENT_COMBATMG_MK2_CLIP_01"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CLIP_01"),
            ["COMPONENT_COMBATMG_MK2_CLIP_02"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CLIP_02"),
            ["COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING"),
            ["COMPONENT_COMBATMG_MK2_CLIP_FMJ"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CLIP_FMJ"),
            ["COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY"),
            ["COMPONENT_COMBATMG_MK2_CLIP_TRACER"] = (uint)GetHashKey("COMPONENT_COMBATMG_MK2_CLIP_TRACER"),
            ["COMPONENT_COMBATPDW_CLIP_01"] = (uint)GetHashKey("COMPONENT_COMBATPDW_CLIP_01"),
            ["COMPONENT_COMBATPDW_CLIP_02"] = (uint)GetHashKey("COMPONENT_COMBATPDW_CLIP_02"),
            ["COMPONENT_COMBATPDW_CLIP_03"] = (uint)GetHashKey("COMPONENT_COMBATPDW_CLIP_03"),
            ["COMPONENT_COMPACTRIFLE_CLIP_01"] = (uint)GetHashKey("COMPONENT_COMPACTRIFLE_CLIP_01"),
            ["COMPONENT_COMPACTRIFLE_CLIP_02"] = (uint)GetHashKey("COMPONENT_COMPACTRIFLE_CLIP_02"),
            ["COMPONENT_COMPACTRIFLE_CLIP_03"] = (uint)GetHashKey("COMPONENT_COMPACTRIFLE_CLIP_03"),
            ["COMPONENT_GUSENBERG_CLIP_01"] = (uint)GetHashKey("COMPONENT_GUSENBERG_CLIP_01"),
            ["COMPONENT_GUSENBERG_CLIP_02"] = (uint)GetHashKey("COMPONENT_GUSENBERG_CLIP_02"),
            ["COMPONENT_HEAVYPISTOL_CLIP_01"] = (uint)GetHashKey("COMPONENT_HEAVYPISTOL_CLIP_01"),
            ["COMPONENT_HEAVYPISTOL_CLIP_02"] = (uint)GetHashKey("COMPONENT_HEAVYPISTOL_CLIP_02"),
            ["COMPONENT_HEAVYPISTOL_VARMOD_LUXE"] = (uint)GetHashKey("COMPONENT_HEAVYPISTOL_VARMOD_LUXE"),
            ["COMPONENT_HEAVYSHOTGUN_CLIP_01"] = (uint)GetHashKey("COMPONENT_HEAVYSHOTGUN_CLIP_01"),
            ["COMPONENT_HEAVYSHOTGUN_CLIP_02"] = (uint)GetHashKey("COMPONENT_HEAVYSHOTGUN_CLIP_02"),
            ["COMPONENT_HEAVYSHOTGUN_CLIP_03"] = (uint)GetHashKey("COMPONENT_HEAVYSHOTGUN_CLIP_03"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CAMO"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_02"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CAMO_02"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_03"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CAMO_03"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_04"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CAMO_04"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_05"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CAMO_05"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_06"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CAMO_06"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_07"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CAMO_07"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_08"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CAMO_08"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_09"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CAMO_09"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_10"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CAMO_10"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01"),
            ["COMPONENT_HEAVYSNIPER_MK2_CLIP_01"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CLIP_01"),
            ["COMPONENT_HEAVYSNIPER_MK2_CLIP_02"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CLIP_02"),
            ["COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING"),
            ["COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE"),
            ["COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ"),
            ["COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY"] = (uint)GetHashKey("COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY"),
            ["COMPONENT_KNUCKLE_VARMOD_BALLAS"] = (uint)GetHashKey("COMPONENT_KNUCKLE_VARMOD_BALLAS"),
            ["COMPONENT_KNUCKLE_VARMOD_BASE"] = (uint)GetHashKey("COMPONENT_KNUCKLE_VARMOD_BASE"),
            ["COMPONENT_KNUCKLE_VARMOD_DIAMOND"] = (uint)GetHashKey("COMPONENT_KNUCKLE_VARMOD_DIAMOND"),
            ["COMPONENT_KNUCKLE_VARMOD_DOLLAR"] = (uint)GetHashKey("COMPONENT_KNUCKLE_VARMOD_DOLLAR"),
            ["COMPONENT_KNUCKLE_VARMOD_HATE"] = (uint)GetHashKey("COMPONENT_KNUCKLE_VARMOD_HATE"),
            ["COMPONENT_KNUCKLE_VARMOD_KING"] = (uint)GetHashKey("COMPONENT_KNUCKLE_VARMOD_KING"),
            ["COMPONENT_KNUCKLE_VARMOD_LOVE"] = (uint)GetHashKey("COMPONENT_KNUCKLE_VARMOD_LOVE"),
            ["COMPONENT_KNUCKLE_VARMOD_PIMP"] = (uint)GetHashKey("COMPONENT_KNUCKLE_VARMOD_PIMP"),
            ["COMPONENT_KNUCKLE_VARMOD_PLAYER"] = (uint)GetHashKey("COMPONENT_KNUCKLE_VARMOD_PLAYER"),
            ["COMPONENT_KNUCKLE_VARMOD_VAGOS"] = (uint)GetHashKey("COMPONENT_KNUCKLE_VARMOD_VAGOS"),
            ["COMPONENT_MACHINEPISTOL_CLIP_01"] = (uint)GetHashKey("COMPONENT_MACHINEPISTOL_CLIP_01"),
            ["COMPONENT_MACHINEPISTOL_CLIP_02"] = (uint)GetHashKey("COMPONENT_MACHINEPISTOL_CLIP_02"),
            ["COMPONENT_MACHINEPISTOL_CLIP_03"] = (uint)GetHashKey("COMPONENT_MACHINEPISTOL_CLIP_03"),
            ["COMPONENT_MARKSMANRIFLE_CLIP_01"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_CLIP_01"),
            ["COMPONENT_MARKSMANRIFLE_CLIP_02"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_CLIP_02"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CAMO"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_02"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CAMO_02"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_03"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CAMO_03"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_04"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CAMO_04"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_05"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CAMO_05"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_06"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CAMO_06"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_07"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CAMO_07"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_08"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CAMO_08"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_09"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CAMO_09"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_10"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CAMO_10"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CLIP_01"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CLIP_01"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CLIP_02"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CLIP_02"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER"),
            ["COMPONENT_MARKSMANRIFLE_VARMOD_LUXE"] = (uint)GetHashKey("COMPONENT_MARKSMANRIFLE_VARMOD_LUXE"),
            ["COMPONENT_MINISMG_CLIP_01"] = (uint)GetHashKey("COMPONENT_MINISMG_CLIP_01"),
            ["COMPONENT_MINISMG_CLIP_02"] = (uint)GetHashKey("COMPONENT_MINISMG_CLIP_02"),
            ["COMPONENT_PISTOL_MK2_CAMO"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CAMO"),
            ["COMPONENT_PISTOL_MK2_CAMO_02"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CAMO_02"),
            ["COMPONENT_PISTOL_MK2_CAMO_03"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CAMO_03"),
            ["COMPONENT_PISTOL_MK2_CAMO_04"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CAMO_04"),
            ["COMPONENT_PISTOL_MK2_CAMO_05"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CAMO_05"),
            ["COMPONENT_PISTOL_MK2_CAMO_06"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CAMO_06"),
            ["COMPONENT_PISTOL_MK2_CAMO_07"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CAMO_07"),
            ["COMPONENT_PISTOL_MK2_CAMO_08"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CAMO_08"),
            ["COMPONENT_PISTOL_MK2_CAMO_09"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CAMO_09"),
            ["COMPONENT_PISTOL_MK2_CAMO_10"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CAMO_10"),
            ["COMPONENT_PISTOL_MK2_CAMO_IND_01"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CAMO_IND_01"),
            ["COMPONENT_PISTOL_MK2_CLIP_01"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CLIP_01"),
            ["COMPONENT_PISTOL_MK2_CLIP_02"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CLIP_02"),
            ["COMPONENT_PISTOL_MK2_CLIP_FMJ"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CLIP_FMJ"),
            ["COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT"),
            ["COMPONENT_PISTOL_MK2_CLIP_INCENDIARY"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CLIP_INCENDIARY"),
            ["COMPONENT_PISTOL_MK2_CLIP_TRACER"] = (uint)GetHashKey("COMPONENT_PISTOL_MK2_CLIP_TRACER"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_MK2_CAMO"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_02"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_MK2_CAMO_02"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_03"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_MK2_CAMO_03"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_04"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_MK2_CAMO_04"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_05"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_MK2_CAMO_05"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_06"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_MK2_CAMO_06"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_07"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_MK2_CAMO_07"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_08"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_MK2_CAMO_08"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_09"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_MK2_CAMO_09"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_10"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_MK2_CAMO_10"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CLIP_01"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_MK2_CLIP_01"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY"] = (uint)GetHashKey("COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY"),
            ["COMPONENT_REVOLVER_MK2_CAMO"] = (uint)GetHashKey("COMPONENT_REVOLVER_MK2_CAMO"),
            ["COMPONENT_REVOLVER_MK2_CAMO_02"] = (uint)GetHashKey("COMPONENT_REVOLVER_MK2_CAMO_02"),
            ["COMPONENT_REVOLVER_MK2_CAMO_03"] = (uint)GetHashKey("COMPONENT_REVOLVER_MK2_CAMO_03"),
            ["COMPONENT_REVOLVER_MK2_CAMO_04"] = (uint)GetHashKey("COMPONENT_REVOLVER_MK2_CAMO_04"),
            ["COMPONENT_REVOLVER_MK2_CAMO_05"] = (uint)GetHashKey("COMPONENT_REVOLVER_MK2_CAMO_05"),
            ["COMPONENT_REVOLVER_MK2_CAMO_06"] = (uint)GetHashKey("COMPONENT_REVOLVER_MK2_CAMO_06"),
            ["COMPONENT_REVOLVER_MK2_CAMO_07"] = (uint)GetHashKey("COMPONENT_REVOLVER_MK2_CAMO_07"),
            ["COMPONENT_REVOLVER_MK2_CAMO_08"] = (uint)GetHashKey("COMPONENT_REVOLVER_MK2_CAMO_08"),
            ["COMPONENT_REVOLVER_MK2_CAMO_09"] = (uint)GetHashKey("COMPONENT_REVOLVER_MK2_CAMO_09"),
            ["COMPONENT_REVOLVER_MK2_CAMO_10"] = (uint)GetHashKey("COMPONENT_REVOLVER_MK2_CAMO_10"),
            ["COMPONENT_REVOLVER_MK2_CAMO_IND_01"] = (uint)GetHashKey("COMPONENT_REVOLVER_MK2_CAMO_IND_01"),
            ["COMPONENT_REVOLVER_MK2_CLIP_01"] = (uint)GetHashKey("COMPONENT_REVOLVER_MK2_CLIP_01"),
            ["COMPONENT_REVOLVER_MK2_CLIP_FMJ"] = (uint)GetHashKey("COMPONENT_REVOLVER_MK2_CLIP_FMJ"),
            ["COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT"] = (uint)GetHashKey("COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT"),
            ["COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY"] = (uint)GetHashKey("COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY"),
            ["COMPONENT_REVOLVER_MK2_CLIP_TRACER"] = (uint)GetHashKey("COMPONENT_REVOLVER_MK2_CLIP_TRACER"),
            ["COMPONENT_REVOLVER_VARMOD_BOSS"] = (uint)GetHashKey("COMPONENT_REVOLVER_VARMOD_BOSS"),
            ["COMPONENT_REVOLVER_VARMOD_GOON"] = (uint)GetHashKey("COMPONENT_REVOLVER_VARMOD_GOON"),
            ["COMPONENT_SMG_MK2_CAMO"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CAMO"),
            ["COMPONENT_SMG_MK2_CAMO_02"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CAMO_02"),
            ["COMPONENT_SMG_MK2_CAMO_03"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CAMO_03"),
            ["COMPONENT_SMG_MK2_CAMO_04"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CAMO_04"),
            ["COMPONENT_SMG_MK2_CAMO_05"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CAMO_05"),
            ["COMPONENT_SMG_MK2_CAMO_06"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CAMO_06"),
            ["COMPONENT_SMG_MK2_CAMO_07"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CAMO_07"),
            ["COMPONENT_SMG_MK2_CAMO_08"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CAMO_08"),
            ["COMPONENT_SMG_MK2_CAMO_09"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CAMO_09"),
            ["COMPONENT_SMG_MK2_CAMO_10"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CAMO_10"),
            ["COMPONENT_SMG_MK2_CAMO_IND_01"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CAMO_IND_01"),
            ["COMPONENT_SMG_MK2_CLIP_01"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CLIP_01"),
            ["COMPONENT_SMG_MK2_CLIP_02"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CLIP_02"),
            ["COMPONENT_SMG_MK2_CLIP_FMJ"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CLIP_FMJ"),
            ["COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT"),
            ["COMPONENT_SMG_MK2_CLIP_INCENDIARY"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CLIP_INCENDIARY"),
            ["COMPONENT_SMG_MK2_CLIP_TRACER"] = (uint)GetHashKey("COMPONENT_SMG_MK2_CLIP_TRACER"),
            ["COMPONENT_SNSPISTOL_CLIP_01"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_CLIP_01"),
            ["COMPONENT_SNSPISTOL_CLIP_02"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_CLIP_02"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CAMO"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_02"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CAMO_02"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_03"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CAMO_03"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_04"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CAMO_04"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_05"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CAMO_05"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_06"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CAMO_06"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_07"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CAMO_07"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_08"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CAMO_08"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_09"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CAMO_09"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_10"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CAMO_10"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_IND_01"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CAMO_IND_01"),
            ["COMPONENT_SNSPISTOL_MK2_CLIP_01"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CLIP_01"),
            ["COMPONENT_SNSPISTOL_MK2_CLIP_02"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CLIP_02"),
            ["COMPONENT_SNSPISTOL_MK2_CLIP_FMJ"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CLIP_FMJ"),
            ["COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT"),
            ["COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY"),
            ["COMPONENT_SNSPISTOL_MK2_CLIP_TRACER"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_MK2_CLIP_TRACER"),
            ["COMPONENT_SNSPISTOL_VARMOD_LOWRIDER"] = (uint)GetHashKey("COMPONENT_SNSPISTOL_VARMOD_LOWRIDER"),
            ["COMPONENT_SPECIALCARBINE_CLIP_01"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_CLIP_01"),
            ["COMPONENT_SPECIALCARBINE_CLIP_02"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_CLIP_02"),
            ["COMPONENT_SPECIALCARBINE_CLIP_03"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_CLIP_03"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CAMO"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_02"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CAMO_02"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_03"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CAMO_03"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_04"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CAMO_04"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_05"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CAMO_05"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_06"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CAMO_06"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_07"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CAMO_07"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_08"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CAMO_08"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_09"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CAMO_09"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_10"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CAMO_10"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01"),
            ["COMPONENT_SPECIALCARBINE_MK2_CLIP_01"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CLIP_01"),
            ["COMPONENT_SPECIALCARBINE_MK2_CLIP_02"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CLIP_02"),
            ["COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING"),
            ["COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ"),
            ["COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY"),
            ["COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER"),
            ["COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER"] = (uint)GetHashKey("COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER"),
            ["COMPONENT_SWITCHBLADE_VARMOD_BASE"] = (uint)GetHashKey("COMPONENT_SWITCHBLADE_VARMOD_BASE"),
            ["COMPONENT_SWITCHBLADE_VARMOD_VAR1"] = (uint)GetHashKey("COMPONENT_SWITCHBLADE_VARMOD_VAR1"),
            ["COMPONENT_SWITCHBLADE_VARMOD_VAR2"] = (uint)GetHashKey("COMPONENT_SWITCHBLADE_VARMOD_VAR2"),
            ["COMPONENT_VINTAGEPISTOL_CLIP_01"] = (uint)GetHashKey("COMPONENT_VINTAGEPISTOL_CLIP_01"),
            ["COMPONENT_VINTAGEPISTOL_CLIP_02"] = (uint)GetHashKey("COMPONENT_VINTAGEPISTOL_CLIP_02"),
        };
        #endregion

        #region weapon component names
        public static readonly Dictionary<string, string> weaponComponentNames = new Dictionary<string, string>()
        {
            ["COMPONENT_PISTOL_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_PISTOL_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_PISTOL_VARMOD_LUXE"] = GetLabelText("WCT_VAR_GOLD"),

            ["COMPONENT_PISTOL50_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_PISTOL50_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_PISTOL50_VARMOD_LUXE"] = GetLabelText("WCT_VAR_SIL"),

            ["COMPONENT_COMBATPISTOL_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_COMBATPISTOL_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER"] = GetLabelText("WCT_VAR_GOLD"),

            ["COMPONENT_APPISTOL_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_APPISTOL_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_APPISTOL_VARMOD_LUXE"] = GetLabelText("WCT_VAR_METAL"),

            ["COMPONENT_SMG_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_SMG_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_SMG_CLIP_03"] = GetLabelText("WCT_CLIP_DRM"),
            ["COMPONENT_AT_SCOPE_MACRO_02"] = GetLabelText("WCT_SCOPE_MAC"),
            ["COMPONENT_SMG_VARMOD_LUXE"] = GetLabelText("WCT_VAR_GOLD"),

            ["COMPONENT_MICROSMG_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_MICROSMG_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_AT_SCOPE_MACRO"] = GetLabelText("WCT_SCOPE_MAC"),
            ["COMPONENT_MICROSMG_VARMOD_LUXE"] = GetLabelText("WCT_VAR_GOLD"),

            ["COMPONENT_ASSAULTSMG_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_ASSAULTSMG_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_AT_SCOPE_MACRO"] = GetLabelText("WCT_SCOPE_MAC"),
            ["COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER"] = GetLabelText("WCT_VAR_GOLD"),

            ["COMPONENT_MG_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_MG_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_AT_SCOPE_SMALL_02"] = GetLabelText("WCT_SCOPE_SML"),
            ["COMPONENT_MG_VARMOD_LOWRIDER"] = GetLabelText("WCT_VAR_GOLD"),

            ["COMPONENT_COMBATMG_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_COMBATMG_CLIP_02"] = GetLabelText("WCT_CLIP2"),

            ["COMPONENT_ASSAULTRIFLE_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_ASSAULTRIFLE_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_ASSAULTRIFLE_CLIP_03"] = GetLabelText("WCT_CLIP_DRM"),
            ["COMPONENT_AT_SCOPE_MACRO"] = GetLabelText("WCT_SCOPE_MAC"),
            ["COMPONENT_ASSAULTRIFLE_VARMOD_LUXE"] = GetLabelText("WCT_VAR_GOLD"),

            ["COMPONENT_CARBINERIFLE_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_CARBINERIFLE_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_CARBINERIFLE_CLIP_03"] = GetLabelText("WCT_CLIP_DRM"),
            ["COMPONENT_CARBINERIFLE_VARMOD_LUXE"] = GetLabelText("WCT_VAR_GOLD"),

            ["COMPONENT_ADVANCEDRIFLE_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_ADVANCEDRIFLE_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE"] = GetLabelText("WCT_VAR_METAL"),

            ["COMPONENT_ASSAULTSHOTGUN_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_ASSAULTSHOTGUN_CLIP_02"] = GetLabelText("WCT_CLIP2"),

            ["COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE"] = GetLabelText("WCT_VAR_METAL"),

            ["COMPONENT_AT_SR_SUPP"] = GetLabelText("WCT_SUPP"),
            ["COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER"] = GetLabelText("WCT_VAR_GOLD"),

            ["COMPONENT_AT_SCOPE_LARGE"] = GetLabelText("WCT_SCOPE_LRG"),
            ["COMPONENT_SNIPERRIFLE_VARMOD_LUXE"] = GetLabelText("WCT_VAR_WOOD"),

            ["COMPONENT_AT_SCOPE_LARGE"] = GetLabelText("WCT_SCOPE_LRG"),

            ["COMPONENT_AT_SCOPE_MACRO"] = GetLabelText("WCT_SCOPE_MAC"),
            ["COMPONENT_AT_SCOPE_MACRO_02"] = GetLabelText("WCT_SCOPE_MAC"),
            ["COMPONENT_AT_SCOPE_SMALL_02"] = GetLabelText("WCT_SCOPE_SML"),
            ["COMPONENT_AT_SCOPE_LARGE"] = GetLabelText("WCT_SCOPE_LRG"),

            ["COMPONENT_AT_SR_SUPP"] = GetLabelText("WCT_SUPP"),


            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO"] = GetLabelText("WCT_CAMO_1"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_02"] = GetLabelText("WCT_CAMO_2"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_03"] = GetLabelText("WCT_CAMO_3"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_04"] = GetLabelText("WCT_CAMO_4"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_05"] = GetLabelText("WCT_CAMO_5"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_06"] = GetLabelText("WCT_CAMO_6"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_07"] = GetLabelText("WCT_CAMO_7"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_08"] = GetLabelText("WCT_CAMO_8"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_09"] = GetLabelText("WCT_CAMO_9"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_10"] = GetLabelText("WCT_CAMO_10"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01"] = GetLabelText("WCT_CAMO_IND"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING"] = GetLabelText("WCT_CLIP_AP"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ"] = GetLabelText("WCT_CLIP_FMJ"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY"] = GetLabelText("WCT_CLIP_INC"),
            ["COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER"] = GetLabelText("WCT_CLIP_TR"),
            ["COMPONENT_AT_AR_AFGRIP"] = GetLabelText("WCT_GRIP"),
            ["COMPONENT_AT_AR_AFGRIP_02"] = GetLabelText("WCT_GRIP"),
            ["COMPONENT_AT_AR_BARREL_01"] = GetLabelText("WCT_BARR"),
            ["COMPONENT_AT_AR_BARREL_02"] = GetLabelText("WCT_BARR2"),
            ["COMPONENT_AT_AR_FLSH"] = GetLabelText("WCT_FLASH"),
            ["COMPONENT_AT_AR_SUPP"] = GetLabelText("WCT_SUPP"),
            ["COMPONENT_AT_AR_SUPP_02"] = GetLabelText("WCT_SUPP"),
            ["COMPONENT_AT_BP_BARREL_01"] = GetLabelText("WCT_BARR"),
            ["COMPONENT_AT_BP_BARREL_02"] = GetLabelText("WCT_BARR2"),
            ["COMPONENT_AT_CR_BARREL_01"] = GetLabelText("WCT_BARR"),
            ["COMPONENT_AT_CR_BARREL_02"] = GetLabelText("WCT_BARR2"),
            ["COMPONENT_AT_MG_BARREL_01"] = GetLabelText("WCT_BARR"),
            ["COMPONENT_AT_MG_BARREL_02"] = GetLabelText("WCT_BARR2"),
            ["COMPONENT_AT_MRFL_BARREL_01"] = GetLabelText("WCT_BARR"),
            ["COMPONENT_AT_MRFL_BARREL_02"] = GetLabelText("WCT_BARR2"),
            ["COMPONENT_AT_MUZZLE_01"] = GetLabelText("WCT_MUZZ1"),
            ["COMPONENT_AT_MUZZLE_02"] = GetLabelText("WCT_MUZZ2"),
            ["COMPONENT_AT_MUZZLE_03"] = GetLabelText("WCT_MUZZ3"),
            ["COMPONENT_AT_MUZZLE_04"] = GetLabelText("WCT_MUZZ4"),
            ["COMPONENT_AT_MUZZLE_05"] = GetLabelText("WCT_MUZZ5"),
            ["COMPONENT_AT_MUZZLE_06"] = GetLabelText("WCT_MUZZ6"),
            ["COMPONENT_AT_MUZZLE_07"] = GetLabelText("WCT_MUZZ7"),
            ["COMPONENT_AT_MUZZLE_08"] = GetLabelText("WCT_MUZZ"),
            ["COMPONENT_AT_MUZZLE_09"] = GetLabelText("WCT_MUZZ9"),
            ["COMPONENT_AT_PI_COMP"] = GetLabelText("WCT_COMP"),
            ["COMPONENT_AT_PI_COMP_02"] = GetLabelText("WCT_COMP"),
            ["COMPONENT_AT_PI_COMP_03"] = GetLabelText("WCT_COMP"),
            ["COMPONENT_AT_PI_FLSH"] = GetLabelText("WCT_FLASH"),
            ["COMPONENT_AT_PI_FLSH_02"] = GetLabelText("WCT_FLASH"),
            ["COMPONENT_AT_PI_FLSH_03"] = GetLabelText("WCT_FLASH"),
            ["COMPONENT_AT_PI_RAIL"] = GetLabelText("WCT_SCOPE_PI"),
            ["COMPONENT_AT_PI_RAIL_02"] = GetLabelText("WCT_SCOPE_PI"),
            ["COMPONENT_AT_PI_SUPP"] = GetLabelText("WCT_SUPP"),
            ["COMPONENT_AT_PI_SUPP_02"] = GetLabelText("WCT_SUPP"),
            ["COMPONENT_AT_SB_BARREL_01"] = GetLabelText("WCT_BARR"),
            ["COMPONENT_AT_SB_BARREL_02"] = GetLabelText("WCT_BARR2"),
            ["COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM"] = GetLabelText("WCT_SCOPE_LRG"),
            ["COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2"] = GetLabelText("WCT_SCOPE_LRG2"),
            ["COMPONENT_AT_SCOPE_LARGE_MK2"] = GetLabelText("WCT_SCOPE_LRG2"),
            ["COMPONENT_AT_SCOPE_MACRO_02_MK2"] = GetLabelText("WCT_SCOPE_MAC2"),
            ["COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2"] = GetLabelText("WCT_SCOPE_MAC2"),
            ["COMPONENT_AT_SCOPE_MACRO_MK2"] = GetLabelText("WCT_SCOPE_MAC2"),
            ["COMPONENT_AT_SCOPE_MAX"] = GetLabelText("WCT_SCOPE_MAX"),
            ["COMPONENT_AT_SCOPE_MEDIUM"] = GetLabelText("WCT_SCOPE_LRG"),
            ["COMPONENT_AT_SCOPE_MEDIUM_MK2"] = GetLabelText("WCT_SCOPE_MED2"),
            ["COMPONENT_AT_SCOPE_NV"] = GetLabelText("WCT_SCOPE_NV"),
            ["COMPONENT_AT_SCOPE_SMALL"] = GetLabelText("WCT_SCOPE_SML"),
            ["COMPONENT_AT_SCOPE_SMALL_MK2"] = GetLabelText("WCT_SCOPE_SML2"),
            ["COMPONENT_AT_SCOPE_SMALL_SMG_MK2"] = GetLabelText("WCT_SCOPE_SML2"),
            ["COMPONENT_AT_SCOPE_THERMAL"] = GetLabelText("WCT_SCOPE_TH"),
            ["COMPONENT_AT_SC_BARREL_01"] = GetLabelText("WCT_BARR"),
            ["COMPONENT_AT_SC_BARREL_02"] = GetLabelText("WCT_BARR2"),
            ["COMPONENT_AT_SIGHTS"] = GetLabelText("WCT_HOLO"),
            ["COMPONENT_AT_SIGHTS_SMG"] = GetLabelText("WCT_HOLO"),
            ["COMPONENT_AT_SR_BARREL_01"] = GetLabelText("WCT_BARR"),
            ["COMPONENT_AT_SR_BARREL_02"] = GetLabelText("WCT_BARR2"),
            ["COMPONENT_AT_SR_SUPP_03"] = GetLabelText("WCT_SUPP"),
            ["COMPONENT_BULLPUPRIFLE_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_BULLPUPRIFLE_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO"] = GetLabelText("WCT_CAMO_1"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_02"] = GetLabelText("WCT_CAMO_2"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_03"] = GetLabelText("WCT_CAMO_3"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_04"] = GetLabelText("WCT_CAMO_4"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_05"] = GetLabelText("WCT_CAMO_5"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_06"] = GetLabelText("WCT_CAMO_6"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_07"] = GetLabelText("WCT_CAMO_7"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_08"] = GetLabelText("WCT_CAMO_8"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_09"] = GetLabelText("WCT_CAMO_9"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_10"] = GetLabelText("WCT_CAMO_10"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01"] = GetLabelText("WCT_CAMO_IND"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING"] = GetLabelText("WCT_CLIP_AP"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ"] = GetLabelText("WCT_CLIP_FMJ"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY"] = GetLabelText("WCT_CLIP_INC"),
            ["COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER"] = GetLabelText("WCT_CLIP_TR"),
            ["COMPONENT_BULLPUPRIFLE_VARMOD_LOW"] = GetLabelText("WCT_VAR_METAL"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO"] = GetLabelText("WCT_CAMO_1"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_02"] = GetLabelText("WCT_CAMO_2"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_03"] = GetLabelText("WCT_CAMO_3"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_04"] = GetLabelText("WCT_CAMO_4"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_05"] = GetLabelText("WCT_CAMO_5"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_06"] = GetLabelText("WCT_CAMO_6"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_07"] = GetLabelText("WCT_CAMO_7"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_08"] = GetLabelText("WCT_CAMO_8"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_09"] = GetLabelText("WCT_CAMO_9"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_10"] = GetLabelText("WCT_CAMO_10"),
            ["COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01"] = GetLabelText("WCT_CAMO_IND"),
            ["COMPONENT_CARBINERIFLE_MK2_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_CARBINERIFLE_MK2_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING"] = GetLabelText("WCT_CLIP_AP"),
            ["COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ"] = GetLabelText("WCT_CLIP_FMJ"),
            ["COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY"] = GetLabelText("WCT_CLIP_INC"),
            ["COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER"] = GetLabelText("WCT_CLIP_TR"),
            ["COMPONENT_COMBATMG_MK2_CAMO"] = GetLabelText("WCT_CAMO_1"),
            ["COMPONENT_COMBATMG_MK2_CAMO_02"] = GetLabelText("WCT_CAMO_2"),
            ["COMPONENT_COMBATMG_MK2_CAMO_03"] = GetLabelText("WCT_CAMO_3"),
            ["COMPONENT_COMBATMG_MK2_CAMO_04"] = GetLabelText("WCT_CAMO_4"),
            ["COMPONENT_COMBATMG_MK2_CAMO_05"] = GetLabelText("WCT_CAMO_5"),
            ["COMPONENT_COMBATMG_MK2_CAMO_06"] = GetLabelText("WCT_CAMO_6"),
            ["COMPONENT_COMBATMG_MK2_CAMO_07"] = GetLabelText("WCT_CAMO_7"),
            ["COMPONENT_COMBATMG_MK2_CAMO_08"] = GetLabelText("WCT_CAMO_8"),
            ["COMPONENT_COMBATMG_MK2_CAMO_09"] = GetLabelText("WCT_CAMO_9"),
            ["COMPONENT_COMBATMG_MK2_CAMO_10"] = GetLabelText("WCT_CAMO_10"),
            ["COMPONENT_COMBATMG_MK2_CAMO_IND_01"] = GetLabelText("WCT_CAMO_IND"),
            ["COMPONENT_COMBATMG_MK2_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_COMBATMG_MK2_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING"] = GetLabelText("WCT_CLIP_AP"),
            ["COMPONENT_COMBATMG_MK2_CLIP_FMJ"] = GetLabelText("WCT_CLIP_FMJ"),
            ["COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY"] = GetLabelText("WCT_CLIP_INC"),
            ["COMPONENT_COMBATMG_MK2_CLIP_TRACER"] = GetLabelText("WCT_CLIP_TR"),
            ["COMPONENT_COMBATPDW_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_COMBATPDW_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_COMBATPDW_CLIP_03"] = GetLabelText("WCT_CLIP_DRM"),
            ["COMPONENT_COMPACTRIFLE_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_COMPACTRIFLE_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_COMPACTRIFLE_CLIP_03"] = GetLabelText("WCT_CLIP_DRM"),
            ["COMPONENT_GUSENBERG_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_GUSENBERG_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_HEAVYPISTOL_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_HEAVYPISTOL_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_HEAVYPISTOL_VARMOD_LUXE"] = GetLabelText("WCT_VAR_WOOD"),
            ["COMPONENT_HEAVYSHOTGUN_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_HEAVYSHOTGUN_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_HEAVYSHOTGUN_CLIP_03"] = GetLabelText("WCT_CLIP_DRM"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO"] = GetLabelText("WCT_CAMO_1"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_02"] = GetLabelText("WCT_CAMO_2"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_03"] = GetLabelText("WCT_CAMO_3"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_04"] = GetLabelText("WCT_CAMO_4"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_05"] = GetLabelText("WCT_CAMO_5"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_06"] = GetLabelText("WCT_CAMO_6"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_07"] = GetLabelText("WCT_CAMO_7"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_08"] = GetLabelText("WCT_CAMO_8"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_09"] = GetLabelText("WCT_CAMO_9"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_10"] = GetLabelText("WCT_CAMO_10"),
            ["COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01"] = GetLabelText("WCT_CAMO_IND"),
            ["COMPONENT_HEAVYSNIPER_MK2_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_HEAVYSNIPER_MK2_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING"] = GetLabelText("WCT_CLIP_AP"),
            ["COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE"] = GetLabelText("WCT_CLIP_EX"),
            ["COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ"] = GetLabelText("WCT_CLIP_FMJ"),
            ["COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY"] = GetLabelText("WCT_CLIP_INC"),
            ["COMPONENT_KNUCKLE_VARMOD_BALLAS"] = GetLabelText("WCT_KNUCK_BG"),
            ["COMPONENT_KNUCKLE_VARMOD_BASE"] = GetLabelText("WCT_KNUCK_01"),
            ["COMPONENT_KNUCKLE_VARMOD_DIAMOND"] = GetLabelText("WCT_KNUCK_DMD"),
            ["COMPONENT_KNUCKLE_VARMOD_DOLLAR"] = GetLabelText("WCT_KNUCK_DLR"),
            ["COMPONENT_KNUCKLE_VARMOD_HATE"] = GetLabelText("WCT_KNUCK_HT"),
            ["COMPONENT_KNUCKLE_VARMOD_KING"] = GetLabelText("WCT_KNUCK_SLG"),
            ["COMPONENT_KNUCKLE_VARMOD_LOVE"] = GetLabelText("WCT_KNUCK_LV"),
            ["COMPONENT_KNUCKLE_VARMOD_PIMP"] = GetLabelText("WCT_KNUCK_02"),
            ["COMPONENT_KNUCKLE_VARMOD_PLAYER"] = GetLabelText("WCT_KNUCK_PC"),
            ["COMPONENT_KNUCKLE_VARMOD_VAGOS"] = GetLabelText("WCT_KNUCK_VG"),
            ["COMPONENT_MACHINEPISTOL_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_MACHINEPISTOL_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_MACHINEPISTOL_CLIP_03"] = GetLabelText("WCT_CLIP_DRM"),
            ["COMPONENT_MARKSMANRIFLE_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_MARKSMANRIFLE_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO"] = GetLabelText("WCT_CAMO_1"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_02"] = GetLabelText("WCT_CAMO_2"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_03"] = GetLabelText("WCT_CAMO_3"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_04"] = GetLabelText("WCT_CAMO_4"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_05"] = GetLabelText("WCT_CAMO_5"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_06"] = GetLabelText("WCT_CAMO_6"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_07"] = GetLabelText("WCT_CAMO_7"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_08"] = GetLabelText("WCT_CAMO_8"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_09"] = GetLabelText("WCT_CAMO_9"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_10"] = GetLabelText("WCT_CAMO_10"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01"] = GetLabelText("WCT_CAMO_10"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING"] = GetLabelText("WCT_CLIP_AP"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ"] = GetLabelText("WCT_CLIP_FMJ"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY"] = GetLabelText("WCT_CLIP_INC"),
            ["COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER"] = GetLabelText("WCT_CLIP_TR"),
            ["COMPONENT_MARKSMANRIFLE_VARMOD_LUXE"] = GetLabelText("WCT_VAR_GOLD"),
            ["COMPONENT_MINISMG_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_MINISMG_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_PISTOL_MK2_CAMO"] = GetLabelText("WCT_CAMO_1"),
            ["COMPONENT_PISTOL_MK2_CAMO_02"] = GetLabelText("WCT_CAMO_2"),
            ["COMPONENT_PISTOL_MK2_CAMO_03"] = GetLabelText("WCT_CAMO_3"),
            ["COMPONENT_PISTOL_MK2_CAMO_04"] = GetLabelText("WCT_CAMO_4"),
            ["COMPONENT_PISTOL_MK2_CAMO_05"] = GetLabelText("WCT_CAMO_5"),
            ["COMPONENT_PISTOL_MK2_CAMO_06"] = GetLabelText("WCT_CAMO_6"),
            ["COMPONENT_PISTOL_MK2_CAMO_07"] = GetLabelText("WCT_CAMO_7"),
            ["COMPONENT_PISTOL_MK2_CAMO_08"] = GetLabelText("WCT_CAMO_8"),
            ["COMPONENT_PISTOL_MK2_CAMO_09"] = GetLabelText("WCT_CAMO_9"),
            ["COMPONENT_PISTOL_MK2_CAMO_10"] = GetLabelText("WCT_CAMO_10"),
            ["COMPONENT_PISTOL_MK2_CAMO_IND_01"] = GetLabelText("WCT_CAMO_IND"),
            ["COMPONENT_PISTOL_MK2_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_PISTOL_MK2_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_PISTOL_MK2_CLIP_FMJ"] = GetLabelText("WCT_CLIP_FMJ"),
            ["COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT"] = GetLabelText("WCT_CLIP_HP"),
            ["COMPONENT_PISTOL_MK2_CLIP_INCENDIARY"] = GetLabelText("WCT_CLIP_INC"),
            ["COMPONENT_PISTOL_MK2_CLIP_TRACER"] = GetLabelText("WCT_CLIP_TR"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO"] = GetLabelText("WCT_CAMO_1"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_02"] = GetLabelText("WCT_CAMO_2"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_03"] = GetLabelText("WCT_CAMO_3"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_04"] = GetLabelText("WCT_CAMO_4"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_05"] = GetLabelText("WCT_CAMO_5"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_06"] = GetLabelText("WCT_CAMO_6"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_07"] = GetLabelText("WCT_CAMO_7"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_08"] = GetLabelText("WCT_CAMO_8"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_09"] = GetLabelText("WCT_CAMO_9"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_10"] = GetLabelText("WCT_CAMO_10"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01"] = GetLabelText("WCT_CAMO_IND"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CLIP_01"] = GetLabelText("WCT_SHELL"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING"] = GetLabelText("WCT_SHELL_AP"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE"] = GetLabelText("WCT_SHELL_EX"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT"] = GetLabelText("WCT_SHELL_HP"),
            ["COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY"] = GetLabelText("WCT_SHELL_INC"),
            ["COMPONENT_REVOLVER_MK2_CAMO"] = GetLabelText("WCT_CAMO_1"),
            ["COMPONENT_REVOLVER_MK2_CAMO_02"] = GetLabelText("WCT_CAMO_2"),
            ["COMPONENT_REVOLVER_MK2_CAMO_03"] = GetLabelText("WCT_CAMO_3"),
            ["COMPONENT_REVOLVER_MK2_CAMO_04"] = GetLabelText("WCT_CAMO_4"),
            ["COMPONENT_REVOLVER_MK2_CAMO_05"] = GetLabelText("WCT_CAMO_5"),
            ["COMPONENT_REVOLVER_MK2_CAMO_06"] = GetLabelText("WCT_CAMO_6"),
            ["COMPONENT_REVOLVER_MK2_CAMO_07"] = GetLabelText("WCT_CAMO_7"),
            ["COMPONENT_REVOLVER_MK2_CAMO_08"] = GetLabelText("WCT_CAMO_8"),
            ["COMPONENT_REVOLVER_MK2_CAMO_09"] = GetLabelText("WCT_CAMO_9"),
            ["COMPONENT_REVOLVER_MK2_CAMO_10"] = GetLabelText("WCT_CAMO_10"),
            ["COMPONENT_REVOLVER_MK2_CAMO_IND_01"] = GetLabelText("WCT_CAMO_IND"),
            ["COMPONENT_REVOLVER_MK2_CLIP_01"] = GetLabelText("WCT_CLIP1_RV"),
            ["COMPONENT_REVOLVER_MK2_CLIP_FMJ"] = GetLabelText("WCT_CLIP_FMJ"),
            ["COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT"] = GetLabelText("WCT_CLIP_HP"),
            ["COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY"] = GetLabelText("WCT_CLIP_INC"),
            ["COMPONENT_REVOLVER_MK2_CLIP_TRACER"] = GetLabelText("WCT_CLIP_TR"),
            ["COMPONENT_REVOLVER_VARMOD_BOSS"] = GetLabelText("WCT_REV_VARB"),
            ["COMPONENT_REVOLVER_VARMOD_GOON"] = GetLabelText("WCT_REV_VARG"),
            ["COMPONENT_SMG_MK2_CAMO"] = GetLabelText("WCT_CAMO_1"),
            ["COMPONENT_SMG_MK2_CAMO_02"] = GetLabelText("WCT_CAMO_2"),
            ["COMPONENT_SMG_MK2_CAMO_03"] = GetLabelText("WCT_CAMO_3"),
            ["COMPONENT_SMG_MK2_CAMO_04"] = GetLabelText("WCT_CAMO_4"),
            ["COMPONENT_SMG_MK2_CAMO_05"] = GetLabelText("WCT_CAMO_5"),
            ["COMPONENT_SMG_MK2_CAMO_06"] = GetLabelText("WCT_CAMO_6"),
            ["COMPONENT_SMG_MK2_CAMO_07"] = GetLabelText("WCT_CAMO_7"),
            ["COMPONENT_SMG_MK2_CAMO_08"] = GetLabelText("WCT_CAMO_8"),
            ["COMPONENT_SMG_MK2_CAMO_09"] = GetLabelText("WCT_CAMO_9"),
            ["COMPONENT_SMG_MK2_CAMO_10"] = GetLabelText("WCT_CAMO_10"),
            ["COMPONENT_SMG_MK2_CAMO_IND_01"] = GetLabelText("WCT_CAMO_IND"),
            ["COMPONENT_SMG_MK2_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_SMG_MK2_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_SMG_MK2_CLIP_FMJ"] = GetLabelText("WCT_CLIP_FMJ"),
            ["COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT"] = GetLabelText("WCT_CLIP_HP"),
            ["COMPONENT_SMG_MK2_CLIP_INCENDIARY"] = GetLabelText("WCT_CLIP_INC"),
            ["COMPONENT_SMG_MK2_CLIP_TRACER"] = GetLabelText("WCT_CLIP_TR"),
            ["COMPONENT_SNSPISTOL_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_SNSPISTOL_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO"] = GetLabelText("WCT_CAMO_1"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_02"] = GetLabelText("WCT_CAMO_2"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_03"] = GetLabelText("WCT_CAMO_3"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_04"] = GetLabelText("WCT_CAMO_4"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_05"] = GetLabelText("WCT_CAMO_5"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_06"] = GetLabelText("WCT_CAMO_6"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_07"] = GetLabelText("WCT_CAMO_7"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_08"] = GetLabelText("WCT_CAMO_8"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_09"] = GetLabelText("WCT_CAMO_9"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_10"] = GetLabelText("WCT_CAMO_10"),
            ["COMPONENT_SNSPISTOL_MK2_CAMO_IND_01"] = GetLabelText("WCT_CAMO_10"),
            ["COMPONENT_SNSPISTOL_MK2_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_SNSPISTOL_MK2_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_SNSPISTOL_MK2_CLIP_FMJ"] = GetLabelText("WCT_CLIP_FMJ"),
            ["COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT"] = GetLabelText("WCT_CLIP_HP"),
            ["COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY"] = GetLabelText("WCT_CLIP_INC"),
            ["COMPONENT_SNSPISTOL_MK2_CLIP_TRACER"] = GetLabelText("WCT_CLIP_TR"),
            ["COMPONENT_SNSPISTOL_VARMOD_LOWRIDER"] = GetLabelText("WCT_VAR_WOOD"),
            ["COMPONENT_SPECIALCARBINE_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_SPECIALCARBINE_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_SPECIALCARBINE_CLIP_03"] = GetLabelText("WCT_CLIP_DRM"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO"] = GetLabelText("WCT_CAMO_1"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_02"] = GetLabelText("WCT_CAMO_2"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_03"] = GetLabelText("WCT_CAMO_3"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_04"] = GetLabelText("WCT_CAMO_4"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_05"] = GetLabelText("WCT_CAMO_5"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_06"] = GetLabelText("WCT_CAMO_6"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_07"] = GetLabelText("WCT_CAMO_7"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_08"] = GetLabelText("WCT_CAMO_8"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_09"] = GetLabelText("WCT_CAMO_9"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_10"] = GetLabelText("WCT_CAMO_10"),
            ["COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01"] = GetLabelText("WCT_CAMO_IND"),
            ["COMPONENT_SPECIALCARBINE_MK2_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_SPECIALCARBINE_MK2_CLIP_02"] = GetLabelText("WCT_CLIP2"),
            ["COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING"] = GetLabelText("WCT_CLIP_AP"),
            ["COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ"] = GetLabelText("WCT_CLIP_FMJ"),
            ["COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY"] = GetLabelText("WCT_CLIP_INC"),
            ["COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER"] = GetLabelText("WCT_CLIP_TR"),
            ["COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER"] = GetLabelText("WCT_VAR_ETCHM"),
            ["COMPONENT_SWITCHBLADE_VARMOD_BASE"] = GetLabelText("WCT_SB_BASE"),
            ["COMPONENT_SWITCHBLADE_VARMOD_VAR1"] = GetLabelText("WCT_SB_VAR1"),
            ["COMPONENT_SWITCHBLADE_VARMOD_VAR2"] = GetLabelText("WCT_SB_VAR2"),
            ["COMPONENT_VINTAGEPISTOL_CLIP_01"] = GetLabelText("WCT_CLIP1"),
            ["COMPONENT_VINTAGEPISTOL_CLIP_02"] = GetLabelText("WCT_CLIP2"),
        };
        #endregion

        #region weapon tints
        public static readonly Dictionary<string, int> WeaponTints = new Dictionary<string, int>()
        {
            ["Black"] = 0,
            ["Green"] = 1,
            ["Gold"] = 2,
            ["Pink"] = 3,
            ["Army"] = 4,
            ["LSPD"] = 5,
            ["Orange"] = 6,
            ["Platinum"] = 7,
        };
        #endregion

        #region weapon mk2 tints
        public static readonly Dictionary<string, int> WeaponTintsMkII = new Dictionary<string, int>()
        {
            ["Classic Black"] = 0,
            ["Classic Gray"] = 1,
            ["Classic Two Tone"] = 2,
            ["Classic White"] = 3,
            ["Classic Beige"] = 4,
            ["Classic Green"] = 5,
            ["Classic Blue"] = 6,
            ["Classic Earth"] = 7,
            ["Classic Brown & Black"] = 8,
            ["Red Contrast"] = 9,
            ["Blue Contrast"] = 10,
            ["Yellow Contrast"] = 11,
            ["Orange Contrast"] = 12,
            ["Bold Pink"] = 13,
            ["Bold Purple & Yellow"] = 14,
            ["Bold Orange"] = 15,
            ["Bold Green & Purple"] = 16,
            ["Bold Red Features"] = 17,
            ["Bold Green Features"] = 18,
            ["Bold Cyan Features"] = 19,
            ["Bold Yellow Features"] = 20,
            ["Bold Red & White"] = 21,
            ["Bold Blue & White"] = 22,
            ["Metallic Gold"] = 23,
            ["Metallic Platinum"] = 24,
            ["Metallic Gray & Lilac"] = 25,
            ["Metallic Purple & Lime"] = 26,
            ["Metallic Red"] = 27,
            ["Metallic Green"] = 28,
            ["Metallic Blue"] = 29,
            ["Metallic White & Aqua"] = 30,
            ["Metallic Red & Yellow"] = 31
        };
        #endregion
        #endregion
    }
}
